config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  # routes for Devise and onmiauth
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # routes for Activa Admin
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # get 'carts/show'
  # get 'products/index'
  # get 'products/show'
  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  namespace :home do
    resource :devise
  end
  
  # Defines the root path route ("/")
  root to: "home#index"
  resources :carts do
    member do
      post :pay
    end
  end
  namespace :purchase do
    resources :checkouts
  end
  resources :products do
    member do
      get :add_to_cart
    end
  end

  get "success", to: "purchase/checkouts#success"
  get "cancel", to: "purchase/checkouts#cancel"
  
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :cartships
    has_many :products, through: :cartships

    def total_price
        cartships.map { |cartship| cartship.quantity * cartship.product.price }.sum
    end
end

app/models/cartship.rb
class Cartship < ApplicationRecord
    belongs_to :product
    belongs_to :cart

    def to_s
        attributes.map{ |k, v| { k => v.to_s } }.inject(:merge)
    end
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :category
    validates :title, presence: true
    validates :price, presence: true

    mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, :omniauthable,
         :omniauth_providers => [:facebook, :google_oauth2]

  mount_uploader :image, ImageUploader

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      # user.name = auth.info.name   # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :load_cart

    def load_cart
      @cart = Cart.find_by(id: session[:cart_id]) if session[:cart_id].present?
    end
    
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = Cart.find(params[:id])
  end

  def pay
    @cart = Cart.find(params[:id])
    Stripe.api_key = Rails.configuration.stripe[:secret_key]
    sessionStripe = Stripe::Checkout::Session.create(
      mode: 'payment',
      customer_email: 'xhosone@gmail.com',
      line_items: [{
        quantity: 1,
        price_data: {
          currency: "usd",
          unit_amount: (@cart.total_price * 100).to_i,
          product_data: {
            name: "name of the product"
          },
        },
      }],
      success_url: root_url + 'success?session_id={CHECKOUT_SESSION_ID}',
      cancel_url: root_url + 'cancel',
    )
    redirect_to sessionStripe.url, allow_other_host: true
  end
end

app/controllers/concerns/pagination.rb
module Pagination
    extend ActiveSupport::Concern

    # def default_per_page
    #     25
    # end
    
    # def page_no
    #     params[:page]&.to_i || 1
    # end

    # def per_page
    #     params[:per_page]&.to_i || default_per_page
    # end

    # def paginate_offset
    #     (page_no-1)*per_page
    # end

    # def paginate
    #     ->(it){ it.limit(per_page).offset(paginate_offset) }
    # end
    def pagination(email)
        puts 'hola perros de mierda '
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include Pagination
  $page = 1
  $pageNumber = 0
  $pageSize = 12
  $totalElements = 0
  $elementPerPage = 0
  def index
    @products = Product.order(:title).to_a
  end

  def show
    pp = params[:page]
    if pp
      $page = pp.to_i <= 1 ? pp.to_i : pp.to_i
    else
      $page = 1
    end
    category = Category.find_by("LOWER(name)= ?", params[:id].downcase)
    $totalElements = category.products.size
    $pageNumber = ($totalElements.to_f / $pageSize.to_f).to_f.ceil
    aux = category.products.limit($pageSize).offset(($page - 1) * 12)
    $elementPerPage = aux.size
    @products = aux
    url = params[:id] # throws error if no url
    puts url
  end

  def add_to_cart
    if session[:cart_id].blank?
      cart = Cart.create(status: "pending")
      session[:cart_id] = cart.id
    else
      cart = Cart.find_by(id: session[:cart_id])
    end
    
    product = Product.find(params[:id])
    cp = cart.cartships.find_by(product_id: product.id)
    if cp.nil?
      cart.cartships.create(product_id: product.id, quantity: 1)
    else
      cp.update(product_id: product.id, quantity: (cp.quantity + 1))
    end
    redirect_to cart
  end
  
end

app/controllers/purchase/checkouts_controller.rb
class Purchase::CheckoutsController < ApplicationController
    def success
        @cart.update(status: "completed")
        session.delete(:cart_id)
        session = Stripe::Checkout::Session.retrieve(params[:session_id])
    end
    def cancel
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    # See https://github.com/omniauth/omniauth/wiki/FAQ#rails-session-is-clobbered-after-callback-on-developer-strategy
    # skip_before_action :verify_authenticity_token, only: :facebook 

    def facebook
        # You need to implement the method below in your model (e.g. app/models/user.rb)
        @user = User.from_omniauth(request.env["omniauth.auth"])

        if @user.persisted?
            sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
            set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
        else
            session["devise.facebook_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
            redirect_to new_user_registration_url
        end
    end

    def failure
        redirect_to root_path
    end

    def google_oauth2
        # You need to implement the method below in your model (e.g. app/models/user.rb)
        @user = User.from_omniauth(request.env['omniauth.auth'])
  
        if @user.persisted?
          flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
          sign_in_and_redirect @user, event: :authentication
        else
          session['devise.google_data'] = request.env['omniauth.auth'].except('extra') # Removing extra as it can overflow some session stores
          redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/show.html.erb
<div class="overflow-x-auto relative pt-10 pb-10">
  <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
    <thead
      class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400"
    >
      <tr>
        <th scope="col" class="py-3 px-6">Nombre de Producto</th>
        <th>Image</th>
        <th scope="col" class="py-3 px-6">Cantidad</th>
        <th scope="col" class="py-3 px-6">Precio</th>
        <th scope="col" class="py-3 px-6">Total</th>
      </tr>
    </thead>
    <tbody>
      <% @cart.cartships.each do |cartship| %>
      <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
        <th
          scope="row"
          class="py-4 px-6 font-medium text-gray-900 whitespace-nowrap dark:text-white"
        >
          <%= cartship.product.title %>
        </th>
        <td>
          <img src="<%= cartship.product.image %>" class="object-cover h-60 w-40"/>
        </td>
        <td class="py-4 px-6"><%= cartship.quantity %></td>
        <td class="py-4 px-6">
          <%= number_to_currency(cartship.product.price) %>
        </td>
        <td class="py-4 px-6">
          <%= number_to_currency(cartship.product.price * cartship.quantity) %>
        </td>
      </tr>
      <% end %>
      <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
        <th
          scope="row"
          class="py-4 px-6 font-medium text-gray-900 whitespace-nowrap dark:text-white"
        >
          Total
        </th>
        <td></td>
        <td></td>
        <td></td>
        <td class="py-4 px-6"><%= number_to_currency(@cart.total_price) %></td>
      </tr>
    </tbody>
  </table>
</div>

<section>
  <div class="product">
    <img src="https://i.imgur.com/EHyR2nP.png" alt="The cover of Stubborn Attachments" />
    <div class="description">
      <h3>Stubborn Attachments</h3>
      <h5>$20.00</h5>
    </div>
  </div>
  <%= form_tag pay_cart_path(@cart), method: :post, data: { turbo: false } do %>
    <%= button_tag "Pagar con Tarjeta", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full" %>
    <!-- <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description="sdf dfdfdmfkdfkdfd "
            data-amount="1000"
            data-email="xhosfirst@gmail.com"
            data-bitcoin="true" 
            data-locale="auto"></script> -->
  <% end %>
</section>

app/views/home/index.html.erb
<div class="w-full">
  <div class="container max-auto w-full">
    <div class="grid grid-cols-2">
      <div><%= image_tag "product1.png", class: "image-size" %></div>
      <!-- ... -->
      <div>
        <div class="grid grid-cols-3">
          <div>
            <%= image_tag "products/product2.png", class: "image-size-fifty" %>
          </div>
          <div>
            <%= image_tag "products/product3.png", class: "image-size-fifty" %>
          </div>
          <div>
            <%= image_tag "products/product4.png", class: "image-size-fifty" %>
          </div>
          <div>
            <%= image_tag "products/product5.png", class: "image-size-fifty" %>
          </div>
          <div>
            <%= image_tag "products/product6.png", class: "image-size-fifty" %>
          </div>
          <div>
            <%= image_tag "products/product7.png", class: "image-size-fifty" %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <section>
    <div class="container max-auto px-20 pt-20 pb-20">
      <div class="grid grid-cols-3 px-20 gap-20">
        <div class="max-w-sm rounded overflow-hidden">
          <%= image_tag "icon/icon1.png", class:"w-full" %>
          <div class="px-6 py-4">
            <div class="font-bold text-xl mb-2">ECO-FRIENDLY</div>
            <p class="text-gray-700 text-base">
              Nuestros productos son 100% amigables con el medio ambiente,
              porque reciclamos ropa y utilizamos tintas en base a (cuenteo).
            </p>
          </div>
        </div>
        <div class="max-w-sm rounded overflow-hidden">
          <%= image_tag "icon/icon2.png", class:"w-full" %>
          <div class="px-6 py-4">
            <div class="font-bold text-xl mb-2">FORMAS DE PAGO</div>
            <p class="text-gray-700 text-base">
              Puedes pagar con tu tarjeta de débito/crédito en Webpay o mediante
              transferencia a nuestra cuenta RUT.
            </p>
          </div>
        </div>
        <div class="max-w-sm rounded overflow-hidden">
          <%= image_tag "icon/icon3.png", class:"w-full" %>
          <div class="px-6 py-4">
            <div class="font-bold text-xl mb-2">SERIGRAFÍA ARTESANAL</div>
            <p class="text-gray-700 text-base">
              Nuestra serigrafía es totalmente artesanal, no sé, cuenteo sobre
              el método y las tintas blabla..
            </p>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section>
    <div class="container max-auto px-20 pb-10">
      <div class="flex items-center py-4">
        <div class="flex-grow h-px bg-gray-400"></div>
        <span class="flex-shrink text-2xl px-4 font-light"
          >REVISA NUESTROS ÚLTIMOS PRODUCTOS</span
        >
        <div class="flex-grow h-px bg-gray-400"></div>
      </div>

      <div class="grid grid-cols-5 gap-5 pt-10">
        <div class="max-w-sm rounded overflow-hidden">
          <%= image_tag "clothes/prod1.png", class:"w-full" %>
          <div class="py-4">
            <p class="text-gray-700 text-base">
              Gorro Tanjiro Kimetsu no Yaiba
            </p>
            <p class="text-gray-700 text-base">$5.000</p>
          </div>
        </div>
        <div class="max-w-sm rounded overflow-hidden">
          <%= image_tag "clothes/prod2.png", class:"w-full" %>
          <div class="py-4">
            <p class="text-gray-700 text-base">Polera Misa Death Note</p>
            <p class="text-gray-700 text-base">$5.000</p>
          </div>
        </div>
        <div class="max-w-sm rounded overflow-hidden">
          <%= image_tag "clothes/prod3.png", class:"w-full" %>
          <div class="py-4">
            <p class="text-gray-700 text-base">
              Polera Jojo’s Bizarre Adventure
            </p>
            <p class="text-gray-700 text-base">$5.000</p>
          </div>
        </div>
        <div class="max-w-sm rounded overflow-hidden">
          <%= image_tag "clothes/prod4.png", class:"w-full" %>
          <div class="py-4">
            <p class="text-gray-700 text-base">Polera Sukuna Jujutsu Kaisen</p>
            <p class="text-gray-700 text-base">$5.000</p>
          </div>
        </div>
        <div class="max-w-sm rounded overflow-hidden">
          <%= image_tag "clothes/prod5.png", class:"w-full" %>
          <div class="py-4">
            <p class="text-gray-700 text-base">Polera rosada Misa Amane</p>
            <p class="text-gray-700 text-base">$5.000</p>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section>
    <div class="container max-auto px-20 pb-20">
      <div class="flex items-center py-4">
        <div class="flex-grow h-px color-secondary"></div>
        <span class="flex-shrink text-2xl px-4 font-light"
          >¡SÍGUENOS EN INSTAGRAM!</span
        >
        <div class="flex-grow h-px color-secondary"></div>
      </div>
      <div
        class="grid grid-flow-row-dense grid-cols-3 grid-rows-1 px-20 gap-5 pt-10"
      >
        <div class="flex">
          <div
            class="max-w-sm rounded overflow-hidden shadow-lg w-full"
            style="background: #75bc74"
          >
            <%= image_tag "logo.svg", size:"60x70", class:"w-full", style:
            "height: 10rem " %>
            <div class="px-6 py-4">
              <div class="font-bold text-xl mb-2 text-center">
                @eco.darkness
              </div>
              <p class="text-gray-700 text-base">
                12 publicaciones 5 seguidores 5 seguidos
              </p>
              <div class="flex justify-center">
                <button
                  class="bg-gray-300 hover:bg-gray-400 text-gray-800 font-bold py-2 px-4 rounded inline-flex items-center"
                >
                  <span>Seguir</span>
                </button>
              </div>
              <p class="text-gray-700 text-base">Tienda de ropa reciclada♻️</p>
              <p class="text-gray-700 text-base">
                Estudiantes de diseño emprendiendo☠
              </p>
              <p class="text-gray-700 text-base">
                🚫Sólo es un trabajo no vendemos🚫
              </p>
            </div>
          </div>
        </div>
        <!-- ... -->
        <div class="col-span-2">
          <div class="grid grid-cols-3 gap-3">
            <div>
              <%= image_tag "products/product2.png", class:
              "image-size-fifty-si" %>
            </div>
            <div>
              <%= image_tag "products/product3.png", class:
              "image-size-fifty-si" %>
            </div>
            <div>
              <%= image_tag "products/product4.png", class:
              "image-size-fifty-si" %>
            </div>
            <div>
              <%= image_tag "products/product5.png", class:
              "image-size-fifty-si" %>
            </div>
            <div>
              <%= image_tag "products/product6.png", class:
              "image-size-fifty-si" %>
            </div>
            <div>
              <%= image_tag "products/product7.png", class:
              "image-size-fifty-si" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebStore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <!-- <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %> -->
    <%= javascript_importmap_tags %>
    <script src="https://js.stripe.com/v3/"></script>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <main class="container mx-auto" style="min-height: 65vh">
      <%= yield %>
    </main>
    <%= render 'shared/fotter' %>
  </body>
</html>

app/views/purchase/checkouts/cancel.html.erb
<div class="max-w-xl mx-auto p-8 rounded-xl shadow-xl mt-6">
    <div class="h-[200px] bg-gray-100 overflow-hidden mb-6 rounded-lg">
      <img
        src="https://source.unsplash.com/random/800x400"
        class="bg-gray-100 object-cover rounded-lg"
      />
    </div>
    <div>
      <h1 class="font-black text-3xl mb-3 text-center">La compra se cancelo,</h1>
      <%= link_to "Continue", root_path, class: "px-3 py-4 bg-black no-underline block w-full text-center rounded font-bold text-white shadow-sm" %>
    </div>
  </div>
  

app/views/purchase/checkouts/success.html.erb
<div class="max-w-xl mx-auto p-8 rounded-xl shadow-xl mt-6">
  <div class="h-[200px] bg-gray-100 overflow-hidden mb-6 rounded-lg">
    <img
      src="https://source.unsplash.com/random/800x400"
      class="bg-gray-100 object-cover rounded-lg"
    />
  </div>
  <div>
    <h1 class="font-black text-3xl mb-3 text-center">Thanks for subscribing,</h1>
    <%= link_to "Continue", root_path, class: "px-3 py-4 bg-black no-underline block w-full text-center rounded font-bold text-white shadow-sm" %>
  </div>
</div>

app/views/shared/_fotter.html.erb
<footer
  id="fotter"
  class=" p-4 bg-white color-secondary shadow md:px-6 md:py-8 dark:bg-gray-900"
>
  <div class="flex justify-center px-20 pb-10">
    <%= image_tag "banner.png", style: "width: 35%" %>
  </div>

  <span class="block text-sm sm:text-center dark:text-gray-400">
    SOBRE LA TIENDA FORMAS DE ENTREGA FRENTE AL COVID-19 TÉRMINOS Y CONDICIONES
  </span>
  <span class="block text-sm sm:text-center dark:text-gray-400">
    Eco Darkness Tienda © Todos los derechos reservados 2021
  </span>
</footer>